#!/bin/bash
#
# intended to be included at login or startup time by bashrc.
#

[[ -n "${debug}" ]] && echo ./bash_set_path

temp=""
for i in \
    /usr/local/bin \
    /usr/ucb \
    /bin \
    /sbin \
    /usr/bin \
    /usr/sbin \
    /etc \
    /usr/lib \
    /usr/bin/X11 \
    /usr/X11R6/bin \
    /usr/vac/bin \
    ; do
    if [[ -d "$i" ]] ; then
	if [[ -z "$temp" ]] ; then
	    temp=$i
	else
	    temp="$temp:$i"
	fi
    fi
done
PATH="$temp"
# echo $PATH | tr : '\n'
unset temp

#
# Try and put our home/bin directory first and then our dfs home directory.
#
if [[ -d /:/home/$USER/bin ]] ; then
    prepend-path "$( cd /:/home/${USER}/bin ; /bin/pwd )"
fi
if echo $HOME | egrep -s /gsa > /dev/null ; then
    prepend-path $HOME/bin
fi
if [[ -d /home/"${USER}"/bin ]] ; then
    prepend-path /home/"${USER}"/bin
fi
if [[ -d /Users/"${USER}"/bin ]] ; then
    prepend-path /Users/"${USER}"/bin
fi
prepend-path .

export VALID_PATH_SET=t
